/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'PMSM_DEV40V2.1' 
 * Target:  'PMSM_DEV40V2.1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "at32m412_416.h"



#endif /* RTE_COMPONENTS_H */
